apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedemoapp
  labels:
    app: kubedemoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubedemoapp
  template:
    metadata:
      labels:
        app: kubedemoapp
    spec:
      containers:
        - name: kubedemoapp
          image: sowmya959/sample1:kubeimage1
          ports:
            - containerPort: 5000